spring:
  profiles:
    active: dev
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xieVictory
    # 设置jwt过期时间
    admin-ttl: 36000000 #10 hour
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: xieVictory
    user-ttl: 36000000 #10 hour
    user-token-name: authentication

  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

  logging:
    level:
      org:
        springframework: DEBUG